<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Builder;
use Illuminate\Database\Eloquent\Model;

class Good extends Model
{
    //商品模型
    protected $fillable=['active_id','title','description','img','price_normal','price_discount','num_total','status'];
    public static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub
        static::addGlobalScope('status_good',function (Builder $builder){
            $builder->where('status','=','1');
            $builder->where('num_total','>=','1');
        });
    }
    //所属活动
    public function active(){
        return $this->belongsTo(Active::class,'active_id','id');
    }
    //验证库存
    public function checkNum($num){
        if($this->num_total<$num){
            return false;
        }else{
            return true;
        }
    }
    //更新库存
    public function updateNum($num){
       return $this->update(['num_total'=>$this->num_total-$num]);
    }
}
